### ISSUE TITLE
pool module does not start

### ISSUE THREAD

**Issue by RomanSzabados** [Snipa22/nodejs-pool#134] opened 2017-10-17 18:44 UTC
Hi,

I have tried a clean install on Ubuntu 16.04.3 LTS with HWE kernel and all seems to work fine, except the pool module does not start:

pm2 status
┌──────────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬────────────┬──────┬──────────┐
│ App name     │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem        │ user │ watching │
├──────────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼────────────┼──────┼──────────┤
│ api          │ 1  │ fork │ 4049 │ online │ 1       │ 50s    │ 0%  │ 49.5 MB    │ root │ disabled │
│ blockManager │ 2  │ fork │ 3618 │ online │ 0       │ 54s    │ 0%  │ 448.6 MB   │ root │ disabled │
│ longRunner   │ 6  │ fork │ 3853 │ online │ 0       │ 52s    │ 0%  │ 155.0 MB   │ root │ disabled │
│ payments     │ 4  │ fork │ 3683 │ online │ 0       │ 53s    │ 0%  │ 47.4 MB    │ root │ disabled │
│ pool         │ 7  │ fork │ 9584 │ online │ 41      │ 0s     │ 1%  │ 40.7 MB    │ root │ disabled │
│ remoteShare  │ 5  │ fork │ 3819 │ online │ 0       │ 53s    │ 0%  │ 47.9 MB    │ root │ disabled │
│ worker       │ 3  │ fork │ 3650 │ online │ 0       │ 54s    │ 0%  │ 51.8 MB    │ root │ disabled │
└──────────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴────────────┴──────┴──────────┘
 Module activated
┌───────────────┬─────────┬────────────┬────────┬─────────┬─────┬─────────────┬──────┐
│ Module        │ version │ target PID │ status │ restart │ cpu │ memory      │ user │
├───────────────┼─────────┼────────────┼────────┼─────────┼─────┼─────────────┼──────┤
│ pm2-logrotate │ 2.2.0   │ N/A        │ online │ 0       │ 0%  │ 36.941 MB   │ root │
└───────────────┴─────────┴────────────┴────────┴─────────┴─────┴─────────────┴──────┘

pool was restarted 41 times... So i try to run it manually:

node init.js --module=pool
Master cluster setting up 10 workers...
Did not send e-mail successfully!  Response: undefined Response: undefined
Worker 11635 is online
Worker 11629 is online
Worker 11639 is online
Worker 11660 is online
Worker 11642 is online
Worker 11671 is online
Worker 11677 is online
Worker 11648 is online
Worker 11655 is online
Worker 11678 is online
/home/monero/nodejs-pool/lib/coins/xmr.js:83
            return callback(err, body);
                            ^

ReferenceError: err is not defined
    at /home/monero/nodejs-pool/lib/coins/xmr.js:83:29
    at /home/monero/nodejs-pool/lib/support.js:103:20
    at Object.parseBody (/home/monero/nodejs-pool/node_modules/request-json/main.js:74:12)
    at Request._callback (/home/monero/nodejs-pool/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/home/monero/nodejs-pool/node_modules/request-json/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/monero/nodejs-pool/node_modules/request-json/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/monero/nodejs-pool/node_modules/request-json/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Could this be a bug, or did i just screw something?
Thank you.

**Comment by Snipa22** [comment] 2017-10-17 18:48
Huh, didn't expect it to close it like that.  Just pushed the fix in, please pull and retry. :)

**Closed** 2017-10-17 18:47 UTC

**Comment by RomanSzabados** [comment] 2017-10-17 18:50
@Snipa22 you rock! It works. Thank you.

**Comment by ArqTras** [comment] 2017-11-08 14:52
When trying to start pool module i get restarts and this info
I'm doing something wrong? 
Fresh install coin aeon
> 2017-11-08 15:46 +01:00: (Master) Queue debug state: 0 items in the queue 0 items being processed
7|pool     | 2017-11-08 15:46 +01:00: TypeError: Cannot read property 'height' of undefined
7|pool     |     at Timeout._onTimeout (/home/arek/nodejs-pool/lib/pool.js:819:114)
7|pool     |     at ontimeout (timers.js:365:14)
7|pool     |     at tryOnTimeout (timers.js:237:5)
7|pool     |     at Timer.listOnTimeout (timers.js:207:5)
7|pool     | 2017-11-08 15:46 +01:00: Master cluster setting up 4 workers...
7|pool     | 2017-11-08 15:46 +01:00: Did not send e-mail successfully!  Response: undefined Response: undefined
7|pool     | 2017-11-08 15:46 +01:00: Worker 18160 is online
7|pool     | 2017-11-08 15:46 +01:00: Worker 18172 is online
7|pool     | 2017-11-08 15:46 +01:00: Worker 18166 is online
7|pool     | 2017-11-08 15:46 +01:00: Worker 18178 is online
7|pool     | 2017-11-08 15:46 +01:00: (Worker 1 - 18160) Started server on port: 3333
7|pool     | 2017-11-08 15:46 +01:00: (Worker 1 - 18160) Started server on port: 5555
7|pool     | 2017-11-08 15:46 +01:00: (Worker 1 - 18160) Started server on port: 7777
7|pool     | 2017-11-08 15:46 +01:00: (Worker 1 - 18160) Started server on port: 9000

**Comment by jimoquinn** [comment] 2017-11-25 14:03
@ArqTras, I believe that error "TypeError: Cannot read property 'height' of undefined" is caused by the global.support.rpcDaemon() call failing in pool.js.  I _think_ was able to fix this by adjusting the IP address for bind_ip in my coin_confg.js.  Not sure if this is the same problem that is causing your error, but check your pool log files and the daemon log files for hints.

**Comment by ArqTras** [comment] 2017-11-25 15:40
I solved this by typing correct address in pool wallet
